"""add_last_enriched_at

Revision ID: 13c0b57f7284
Revises: 5a695893eeb6
Create Date: 2026-06-12 23:04:40.939904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c0b57f7284'
down_revision: Union[str, Sequence[str], None] = '5a695893eeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('last_enriched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'last_enriched_at')
    # ### end Alembic commands ###
