"""add_not_found_flags

Revision ID: 2374bb86f742
Revises: 0877018e7f99
Create Date: 2026-06-18 15:59:23.336260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2374bb86f742'
down_revision: Union[str, Sequence[str], None] = '0877018e7f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_background_tasks_owner_id'), 'background_tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_playlists_owner_id'), 'playlists', ['owner_id'], unique=False)
    op.add_column('tracks', sa.Column('lyrics_not_found', sa.Boolean(), nullable=True))
    op.add_column('tracks', sa.Column('ai_not_found', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tracks_owner_id'), 'tracks', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_owner_id'), table_name='tracks')
    op.drop_column('tracks', 'ai_not_found')
    op.drop_column('tracks', 'lyrics_not_found')
    op.drop_index(op.f('ix_playlists_owner_id'), table_name='playlists')
    op.drop_index(op.f('ix_background_tasks_owner_id'), table_name='background_tasks')
    # ### end Alembic commands ###
