"""add_deep_data

Revision ID: 5a695893eeb6
Revises: e98a3c9d805a
Create Date: 2026-06-12 14:22:24.466869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a695893eeb6'
down_revision: Union[str, Sequence[str], None] = 'e98a3c9d805a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_history_id'), 'play_history', ['id'], unique=False)
    op.add_column('tracks', sa.Column('bpm', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('energy', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('danceability', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('valence', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('popularity', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('release_year', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('explicit', sa.Boolean(), nullable=True))
    op.add_column('tracks', sa.Column('lyrics', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'lyrics')
    op.drop_column('tracks', 'explicit')
    op.drop_column('tracks', 'release_year')
    op.drop_column('tracks', 'popularity')
    op.drop_column('tracks', 'valence')
    op.drop_column('tracks', 'danceability')
    op.drop_column('tracks', 'energy')
    op.drop_column('tracks', 'bpm')
    op.drop_index(op.f('ix_play_history_id'), table_name='play_history')
    op.drop_table('play_history')
    # ### end Alembic commands ###
