"""add_track_metadata

Revision ID: 75c3746041b5
Revises: a40538d804b7
Create Date: 2026-06-10 13:41:02.561030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c3746041b5'
down_revision: Union[str, Sequence[str], None] = 'a40538d804b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('album_artist', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'thumbnail_url')
    op.drop_column('tracks', 'album_artist')
    # ### end Alembic commands ###
