"""add_matched_youtube_id

Revision ID: 7c974d8ab8a5
Revises: 13c0b57f7284
Create Date: 2026-06-12 23:17:42.623172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c974d8ab8a5'
down_revision: Union[str, Sequence[str], None] = '13c0b57f7284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('matched_youtube_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'matched_youtube_id')
    # ### end Alembic commands ###
