"""Add youtube tokens

Revision ID: a40538d804b7
Revises: fa86fa3aa38b
Create Date: 2026-06-09 16:55:29.743528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40538d804b7'
down_revision: Union[str, Sequence[str], None] = 'fa86fa3aa38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yt_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('yt_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('yt_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'yt_token_expiry')
    op.drop_column('users', 'yt_refresh_token')
    op.drop_column('users', 'yt_access_token')
    # ### end Alembic commands ###
