"""add_spotify_persistence

Revision ID: e98a3c9d805a
Revises: 75c3746041b5
Create Date: 2026-06-10 14:42:43.145776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98a3c9d805a'
down_revision: Union[str, Sequence[str], None] = '75c3746041b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('spotify_uri', sa.String(), nullable=True))
    op.add_column('users', sa.Column('spotify_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spotify_token_expiry')
    op.drop_column('tracks', 'spotify_uri')
    # ### end Alembic commands ###
