"""Add spotify tokens

Revision ID: fa86fa3aa38b
Revises: e4cc940f63e4
Create Date: 2026-06-09 15:59:33.621249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa86fa3aa38b'
down_revision: Union[str, Sequence[str], None] = 'e4cc940f63e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('spotify_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spotify_refresh_token')
    op.drop_column('users', 'spotify_access_token')
    # ### end Alembic commands ###
